;==================== INT0 Handler ================================>
;==================== INT0 Handler ================================>

timer0:
   push  acc
   push  psw
   push  dpl
   push  dph

; Check if interrupt was generated by set/reset routine.

   jnb   sflag,timer01           ; Set initiated
   clr   sflag                   ; Clear SFLAG
   mov   dptr,#0xC000            ; Address to set SET low
   movx  @dptr,a                 ; Do it.   
   sjmp  timer0_exit
   
timer01:

   jnb   rflag,timer02           ; Reset initiated.
   clr   rflag                   ; Clear RFLAG
   mov   dptr,#0xD000            ; Address to set RESET low
   movx  @dptr,a                 ; Do it.
   sjmp  timer0_exit             ; Exit

timer02:

; Configure Timer0 for interrupt every 1/20 of a second
   mov   tl0,#T0LOW        ; Reload timer
   mov   th0,#T0HIGH

   inc   time0             ; Increment time count
   mov   a,time0           ; Get time count
   cjne  a,#5,timer0_exit  ; 1/5 of a second expired? No then exit
   mov   time0,#0x000      ; Yes, clear the count
   setb  needleflag        ; Set needleflag to write the needle

timer0_exit:
   pop   dph
   pop   dpl
   pop   psw
   pop   acc
   reti
